### ISSUE TITLE
Dim screen option always enabled

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-control-center#1]
It looks like the "dim screen" option in the Power tab has no effect. The screen always dim, no matter how this settings is set.

(Would be interesting to see what this code is calling exactly)

**Comment by kgilmer** [comment]
Looks like it's a dconf value unimplemented by `gnome-flashback`:

```
~$ gsettings get org.gnome.settings-daemon.plugins.power idle-dim
true
~$ find ~/dev/repos/gnome-flashback | xargs grep -HsF "idle-dim"
~$ 
```

Good candidate to be removed from UI.

**Comment by ploum** [comment]
Interesting to know that it’s a gnome-flashback problem.  (with 22.04, my screen started dimming after a few second of inactivity, something I had not before).  

But it might be out of scope of regolith to fix that.

**Comment by ploum** [comment]
In the last upgrade, you tried to remove this option.

But, for whatever reason, I now have *only* this option in the Energy panel. Kind of funny :-)

**Comment by ploum** [comment]
![Capture d’écran du 2022-04-08 12-10-14](https://user-images.githubusercontent.com/1233155/162415223-dbea4137-eb90-4131-af42-395c1dca8a4b.png)

**Comment by kgilmer** [comment]
I reverted the change such that the power tab should be "stock" for now.  I do not see a "dim screen" option in Ubuntu Jammy.  There is another invalid UI element for configuring (I'm guessing) `gnome-shell` UI for battery percentage.  I've created #3 to track that.
